In [1]:
import warnings
import cv2
import os
import copy
from sklearn.externals import joblib
import numpy as np
from keras.models import load_model

Using TensorFlow backend.


In [2]:
# !pip install keras

  Using cached https://files.pythonhosted.org/packages/ad/fd/6bfe87920d7f4fd475acd28500a42482b6b84479832bdc0fe9e589a60ceb/Keras-2.3.1-py2.py3-none-any.whl


In [2]:
model = load_model('cnn0515(imagegenerator, 200, haar cascade).h5')
cascade_file = 'haarcascade_frontface.xml'
cascade = cv2.CascadeClassifier(cascade_file)

capture = cv2.VideoCapture(0)
capture.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
capture.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)
frame_count = 0

while True:
    ret, frame = capture.read()
    frame2 = copy.copy(frame)
    frame_count += 1
    
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    face_list = cascade.detectMultiScale(gray)

    if len(face_list) == 0:
        quit()

    for (x,y,w,h) in face_list:
        roi = frame[y:y+h, x:x+w]
        roi = roi.astype('float32')/255
        imagex = cv2.resize(roi, (200, 200))
        #print(imagex.shape)
        image_data = imagex.reshape(1, 200, 200, 3)

        color = (255, 0, 0)

        pred_y = model.predict(image_data) # --- (*4)
        print(pred_y)

        if np.argmax(pred_y) == 0:
                cv2.rectangle(frame, (x, y), (x+w, y+h), color, thickness=4)
                cv2.putText(frame,'Neutral',(x,y-20),cv2.FONT_ITALIC, 0.5, (255,255,255))  

        elif np.argmax(pred_y) == 1:  
                cv2.rectangle(frame, (x, y), (x+w, y+h), color, thickness=4)
                cv2.putText(frame,'Positive',(x,y-20),cv2.FONT_ITALIC, 0.5, (255,255,255))  
        else:
            np.argmax(pred_y) == 2
            cv2.rectangle(frame, (x, y), (x+w, y+h), color, thickness=4)
            cv2.putText(frame,'Negative',(x,y-20),cv2.FONT_ITALIC, 0.5, (255,255,255))          

    cv2.imshow("VideoFrame", frame) # 윈도우 창에 이미지 띄움
    if cv2.waitKey(1) > 0:       # (time) 은 time 마다 키 입력상태 받아옴
        break   

capture.release()                # 받아온 메모리 해제
cv2.destroyAllWindows() 

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.
[[8.9090242e-04 2.2164768e-05 9.9908698e-01]]
[[1.6459096e-03 6.4024738e-05 9.9829000e-01]]
[[1.0685845e-03 2.5438221e-05 9.9890602e-01]]
[[1.4259417e-03 3.8388564e-05 9.9853563e-01]]
[[3.7499517e-03 5.7505502e-05 9.9619257e-01]]
[[4.5537362e-03 6.3853600e-05 9.9538237e-01]]
[[2.3017020e-03 8.9338806e-05 9.9760890e-01]]
[[3.7251352e-04 1.4161176e-04 9.9948585e-01]]
[[5.0405655e-02 5.8944213e-05 9.4953543e-01]]
[[1.4559329e-04 5.0414860e-04 9.9935025e-01]]
[[3.1436485e-04 1.7640301e-03 9.9792165e-01]]
[[1.0374445e-04 2.4684452e-04 9.9964941e-01]]
[[6.7252025e-05 2.7234526e-04 9.9966037e-01]]
[[1.9174113e-04 3.5947212e-04 9.9944884e-01]]
[[5.9579343e-05 6.2180217e-04 9.9931860e-01]]
[[1.7822198e-04 4.0911484e-04 9.9941266e-01]]
[[2.56587169e-03 1.00869205e-04 9.97333288e-01]]
[[1.2848605e-03 7.7142562e-05 9.9863797e-01]]
[[1.2610600e-04 1.8834256e-05 9.9985504e-01]]
[[2