# 얼굴에서 입 검출하기
> 얼굴을 검출할 때처럼 haar cascade를 사용한다. 

In [105]:
# !pip install visual-logging

  Stored in directory: C:\Users\user\AppData\Local\pip\Cache\wheels\a4\b3\b6\5aa791652042e96702ab7f7a4b7eadc70ffcc776d48668388d
Successfully built visual-logging


In [1]:
# 라이브러리 불러오기
import cv2
import numpy as np
from matplotlib import pyplot as plt
import sys

In [127]:
# 되는 list 실험해보기
cascade_list = ['C:/Users/user/Desktop/data/haarcascade_eye.xml',
                "C:/Users/user/Desktop/data/haarcascade_eye_tree_eyeglasses.xml",
                "C:/Users/user/Desktop/data/haarcascade_frontalface_alt.xml",
                "C:/Users/user/Desktop/data/haarcascade_frontalface_alt_tree.xml",
                "C:/Users/user/Desktop/data/haarcascade_frontalface_alt2.xml",
                "C:/Users/user/Desktop/data/haarcascade_frontalface_default.xml",
                "C:/Users/user/Desktop/data/haarcascade_lefteye_2splits.xml",
                "C:/Users/user/Desktop/data/haarcascade_mcs_lefteye.xml",
                "C:/Users/user/Desktop/data/haarcascade_mcs_nose.xml",
                "C:/Users/user/Desktop/data/haarcascade_mcs_righteye.xml",
                "C:/Users/user/Desktop/data/haarcascade_profileface.xml",
                "C:/Users/user/Desktop/data/haarcascade_righteye_2splits.xml",
                "C:/Users/user/Desktop/data/hogcascade_cars_sideview.xml"
               ]


example_cascade = cv2.CascadeClassifier()
print(example_cascade.load("/cv_data/haarcascade_eye.xml"))

False


In [4]:
eye_cascade = cv2.CascadeClassifier("C:/Users/user/Downloads/cv_data/haarcascade_eye.xml")
print('로드 완료')
print(eye_cascade)

로드 완료
<CascadeClassifier 00000207E27F6870>


In [36]:
img = cv2.imread("C:/Users/user/Desktop/roi/train/E01/200.jpg")
faces = eye_cascade.detectMultiScale(img)

color = (255, 0, 0)
for (x,y,w,h) in faces:
    print(faces)
    print((x, y, w, h))    
#     cv2.rectangle(img, (31,38), (196,110), color, thickness=4) # 오른쪽 눈부터 좌표 검출
    cv2.rectangle(img, (faces[1][0]-10, faces[1][1]-30), (faces[0][0]+faces[0][2]+20, faces[0][1]+faces[0][3]), color,4)

    roi = img[y:y+h, x:x+w]
#     cv2.rectangle(img, (x, y), (x+w, y+h), color, thickness=2)
    
cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[156  78  46  46]
 [ 58  76  53  53]]
(156, 78, 46, 46)
[[156  78  46  46]
 [ 58  76  53  53]]
(58, 76, 53, 53)


In [194]:
cap = cv2.VideoCapture(0)
ds_factor = 0.5

ret, frame = cap.read()
print('실행 완료 1')
frame = cv2.resize(frame, None, fx=ds_factor, fy=ds_factor, interpolation=cv2.INTER_AREA)
print('실행 완료 2')
gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
print('실행 완료 3')

실행 완료 1
실행 완료 2
실행 완료 3


In [5]:

mouth_rects = mouth_cascade.detectMultiScale(gray, 1.7, 11)
print('실행 완료')
for (x,y,w,h) in mouth_rects:
    y = int(y-0.15*h)
    cv2.rectangle(frame, (x,y), (x+w, y+h), (0, 255, 0), 3)
    break


array([[145, 143, 143, ..., 168, 169, 165],
       [144, 144, 145, ..., 168, 168, 168],
       [144, 145, 145, ..., 167, 167, 168],
       ...,
       [ 23,  23,  21, ..., 100,  99,  99],
       [ 25,  25,  21, ...,  97,  99,  99],
       [ 24,  22,  20, ...,  94,  95,  99]], dtype=uint8)

In [3]:
cascade_path = "/haarcascade_mcs_mouth.xml"
cascade_path2 = 'haarcascade_mcs_eyepair_big.xml' #./data/haarcascade_mcs_eyepair_big.xml
cascade_path3 = 'haarcascade_mcs_eyepair_small.xml' # ./data/haarcascade_mcs_eyepair_small.xml
 
mouth_cascade = cv2.CascadeClassifier(cascade_path)
print('로드 완료')

cap = cv2.VideoCapture(0)
ds_factor = 0.5

while True:
    ret, frame = cap.read()
    print('실행 완료 1')
    frame = cv2.resize(frame, None, fx=ds_factor, fy=ds_factor, interpolation=cv2.INTER_AREA)
    print('실행 완료 2')
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    print('실행 완료 3')
    
    mouth_rects = mouth_cascade.detectMultiScale(gray, 1.7, 11)
    print('실행 완료')
    for (x,y,w,h) in mouth_rects:
        y = int(y-0.15*h)
        cv2.rectangle(frame, (x,y), (x+w, y+h), (0, 255, 0), 3)
        break
        
    cv2.imshow('Mouth Detector', frame)
    
    c = cv2.waitKey(1)
    if c == 27:
        break
        
    cap.release()
    cv2.destroyAllWindows()

로드 완료
실행 완료 1
실행 완료 2
실행 완료 3


error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\objdetect\src\cascadedetect.cpp:1689: error: (-215:Assertion failed) !empty() in function 'cv::CascadeClassifier::detectMultiScale'
